//-------------------------------------------------------------------------------------------------
//
//  File : progress_bar.h
//
//-------------------------------------------------------------------------------------------------
//
// Copyright(c) 2020 Alain Royer.
// Email: aroyer.qc@gmail.com
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
// AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//-------------------------------------------------------------------------------------------------

//---------------------------------------------
// This file was autogenerated by SkinAssembler
//---------------------------------------------

#include "lib_digini.h"
#ifdef DIGINI_USE_GRAFX

const uint32_t progress_bar[18] =
{
    0xFFACB1B3, 0xFF657276, 0xFF6F7D82, 0xFF728186,
    0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186,
    0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186,
    0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186,
    0xFF728186, 0xFFB3B9BB,
};

extern const StaticImageInfo_t SII_progress_bar;
const StaticImageInfo_t SII_progress_bar =
{
    1,
    18,
    4,
    32,
    (uint8_t*)progress_bar,
    18,
    PIXEL_FORMAT_ARGB8888,
    COMPX_COMPRESSION_NONE,
};

//-------------------------------------------------------------------------------------------------

#endif // DIGINI_USE_GRAFX
